stages:
  - install
  - build
  - test
  - deploy

variables:
  NODE_ENV: test # Example environment variable

# Install dependencies
install:
  stage: install
  image: node:18 # Use Node.js Docker image
  script:
    # Debug: List directory structure
    - echo "Checking directory structure during install stage:"
    - ls -R
    - cd IQextract/frontend
    - npm ci # Clean install dependencies for frontend
    - cd ../backend
    - go mod download # Install Go dependencies
  cache:
    key: node-modules-cache
    paths:
      - IQextract/frontend/node_modules/ # Cache node_modules
      - IQextract/backend/pkg/mod/ # Cache Go modules

# Build the project
build:
  stage: build
  image: node:18
  script:
    - echo "Checking directory structure during build stage:"
    - ls -R
    - cd IQextract/frontend
    - npm run build # Build React app
    - cd ../backend
    - go build -o app # Build Go backend
  artifacts:
    paths:
      - IQextract/frontend/dist/ # React build output
      - IQextract/backend/app # Go binary

# Test the project
test:
  stage: test
  image: node:18
  script:
    - echo "Running React unit tests"
    - cd IQextract/frontend
    - npm run test # Run React tests
    - cd ../backend
    - echo "Running Go unit tests"
    - go test ./... # Run Go unit tests

# End-to-End Testing with Playwright
e2e-tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.37.0-focal # Playwright testing image
  script:
    - cd IQextract/frontend
    - npm run test:e2e # Run Playwright tests
  dependencies:
    - build # Ensure the app is built before testing

# Deploy the application
deploy:
  stage: deploy
  image: node:18
  script:
    - echo "Starting both React and Go apps"
    - cd IQextract/frontend
    - npm run start-all # Start both React and Go apps
  only:
    - main # Only deploy on the main branch
